"""Personal-use worker that turns pending research runs into an audit trail.

See Issue #54, Phase 1.5. Run this only on a machine you control, never
inside the public web server process: it is the one piece of this project
allowed to hold a GitHub token, and travel/webapp.py never imports it or
sees that token.

Usage:
  LLM_TRAVEL_AUTO_RESEARCH=1 \
  LLM_TRAVEL_AUTO_WORKER_GITHUB_TOKEN=... \
  LLM_TRAVEL_AUTO_WORKER_GITHUB_REPO=owner/repo \
  LLM_TRAVEL_AUTO_WORKER_GITHUB_ISSUE=54 \
  python scripts/run_auto_research_worker.py [--once]

The GitHub token must be a fine-grained personal access token scoped to
"Issues: write" on this one repository only -- never contents, merge, or
administration scopes. Posting the audit record is optional: if the repo,
issue, or token are not set, this only prints the outcome locally.
"""

import os
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from travel.auto_worker import GITHUB_TOKEN_ENV_VAR, auto_research_enabled, post_audit_comment, process_pending_run
from travel.storage import Repository


def format_audit_body(summary):
    lines = [f"## 自動ワーカー実行記録 (run {summary['run_id']})", "", f"- outcome: `{summary['outcome']}`"]
    lines += [f"- {key}: {value}" for key, value in summary.items() if key not in ("run_id", "outcome")]
    lines += ["", "_Generated by the personal-use auto worker (Issue #54, Phase 1.5); not a saved itinerary._"]
    return "\n".join(lines)


def run_once(repo, workspace, github_repo=None, github_issue=None, github_token=None, poster=None):
    """Process every currently 'requested' run once. Returns the list of summaries."""
    summaries = []
    for run in repo.list_research_runs(state="requested"):
        summary = process_pending_run(repo, run, workspace)
        summaries.append(summary)
        if github_repo and github_issue and github_token:
            body = format_audit_body(summary)
            try:
                if poster is None:
                    post_audit_comment(github_repo, github_issue, github_token, body)
                else:
                    post_audit_comment(github_repo, github_issue, github_token, body, poster=poster)
            except (ValueError, RuntimeError) as exc:
                print(f"warning: could not post audit record for run {run['id']}: {exc}", file=sys.stderr)
    return summaries


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]
    if not auto_research_enabled():
        print('LLM_TRAVEL_AUTO_RESEARCH is not "1", or LLM_TRAVEL_DEPLOYMENT_MODE is "commercial"; refusing to run.', file=sys.stderr)
        return 1
    token = os.environ.get(GITHUB_TOKEN_ENV_VAR, "").strip() or None
    github_repo = os.environ.get("LLM_TRAVEL_AUTO_WORKER_GITHUB_REPO", "").strip() or None
    try:
        github_issue = int(os.environ["LLM_TRAVEL_AUTO_WORKER_GITHUB_ISSUE"])
    except (KeyError, ValueError):
        github_issue = None
    try:
        interval = float(os.environ.get("LLM_TRAVEL_AUTO_WORKER_INTERVAL_SECONDS", "60"))
    except ValueError:
        interval = 60.0
    db_path = os.environ.get("LLM_TRAVEL_DB", "data/travel.sqlite3")
    Path(db_path).parent.mkdir(parents=True, exist_ok=True)
    repo = Repository(db_path)
    try:
        run_forever = "--once" not in argv
        while True:
            for summary in run_once(repo, PROJECT_ROOT, github_repo, github_issue, token):
                print(summary)
            if not run_forever:
                break
            time.sleep(interval)
    finally:
        repo.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
